version: '3.2'

services:
  api:
    build: .
    container_name: api-server
    ports:
      - 8081:8081
    volumes:
      - ./../:/var/www/
    entrypoint: /bin/sh
    command:
      - /start.sh
    tty: true
  db:
    image: postgres
    restart: always
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: passwords
    ports:
      - 5432:5432